import type { RuleSection } from "./types";

export const ACCENT = "#a3be8c";
export const ACCENT_WARM = "#ebcb8b";

export const SUMMARY =
  "A year-long workout game that runs in the yut-hut Discord channel. When you exercise, you check in. The bot turns each check-in into RuneScape-style XP, levels, loot and a shared town. Two check-ins a week keeps you in form. Nothing else is required, and nothing else is rewarded.";

export const STAT_LINE = [
  { label: "The rule", value: "2 a week" },
  { label: "Launch", value: "14 Sep 2026" },
  { label: "Length", value: "52 weeks" },
  { label: "Skills", value: "9" },
];

export const SECTIONS: RuleSection[] = [
  {
    id: "rules",
    label: "The two rules",
    title: "The two rules",
    blocks: [
      { kind: "p", text: "**Check in twice a week.** A week runs Monday to Sunday. Two check-ins in that week puts you \"in form\". Everything else on this page is extra." },
      { kind: "p", text: "**Only players exist.** Until you run `/join`, the bot does not know you are there. It never counts you, names you, or pings you." },
      { kind: "note", text: "Only a check-in earns anything. Chatting, reacting and hanging around the channel earn nothing." },
    ],
  },
  {
    id: "joining",
    label: "Joining",
    title: "Joining",
    blocks: [
      {
        kind: "ul",
        items: [
          "`/join`, or the Join button on the pinned board, makes you a player.",
          "`/leave` retires you. Your sheet is kept. Rejoin whenever you like.",
          "`/expedition weeks:1-8` pauses you for 1 to 8 weeks. Paused weeks do not count against you, and you are left out of the group numbers.",
          "Pings are off until you turn them on with `/pings on` or the Ping me button. Even then you are pinged at most twice a week: the morning post and Sunday's last call.",
        ],
      },
      { kind: "p", text: "People who have not joined never appear in any message." },
    ],
  },
  {
    id: "day",
    label: "How a day works",
    title: "How a day works",
    blocks: [
      {
        kind: "ol",
        items: [
          "The game day runs 3am to 3am Mountain time. A midnight workout counts as today.",
          "8am Mountain: the bot asks **Did you work out in the last 24 hours?** with a **Yes** and a **No** button.",
          "Press Yes when you did. That is the check-in. Press No on a rest day; nothing is lost, and the post shows you answered. `/checkin` is only for adding a note or a photo, before or after a Yes.",
          "The post edits itself as people answer: who said yes, who said no, how many are still to answer. Only players are named.",
          "Every Yes is a **training session** against your Slayer task, scored the way Old School RuneScape scores it. Only you see the receipt: one line, anything only you can act on (a lamp, a quiz, a reward waiting), and buttons for Lamp, Clue, Task, Sheet, Town, Log, Bingo, Shop, Votes.",
          "The morning post starts a **thread** for the day. Each check-in's line goes in there with a **loot card** under it: the session, the bones and drops as RuneScape item icons, the XP by skill, any level-up (`Hitpoints 12 -> 13`), and the task. It looks like an OSRS progress report. The RuneScape level-up scroll shows up for milestone levels only: every tenth, every fifth past 60, every level past 90.",
          "The channel itself only hears from a check-in when you bring a **photo, video or note**: a short post with the media and the quote, and the **Verify** button. Everything else stays in the thread.",
          "7pm Mountain: if anyone has a lamp to rub, points to spend, a vote to cast or a reward waiting on a check-in, the bot posts one **evening reminder** naming them. Anyone on their third day without a check-in is @mentioned in it: tomorrow is day four, and stale. It comes down again at 3am.",
          "Sunday 5pm Mountain: last call. Nobody is named.",
          "Monday: the week closes. Streaks and Rings are settled. From Act 2, the build vote opens.",
          "The 1st of each month: the bot posts a log of the month just gone.",
        ],
      },
      { kind: "note", text: "One check-in per day. Any exercise counts. There are no workout types, so there is nothing to argue about. The bot drives the day; the slash commands are for the things you choose to do, like rubbing a lamp or reading a clue." },
    ],
  },
  {
    id: "fresh",
    label: "Fresh",
    title: "Fresh",
    blocks: [
      { kind: "p", text: "You are **fresh** if you have checked in within the last 4 days." },
      { kind: "p", text: "Fresh players can do things: rub lamps, work on clues, verify other people, change combat style, open the hub, and run the town." },
      { kind: "p", text: "Stale players are told \"Check in to play\". Nothing is taken from you. Your lamps and clues wait." },
    ],
  },
  {
    id: "weight",
    label: "The weight",
    title: "The weight",
    lede: "Each check-in in a week (Monday to Sunday) is worth less than the one before. The first two are worth full value. After that the value drops, on purpose.",
    blocks: [
      {
        kind: "table",
        columns: ["Check-in", "Weight", "Week total"],
        rows: [
          ["1st", "100%", "1.0"],
          ["2nd", "100%", "2.0"],
          ["3rd", "50%", "2.5"],
          ["4th", "50%", "3.0"],
          ["5th", "20%", "3.2"],
          ["6th", "20%", "3.4"],
          ["7th", "20%", "3.6"],
        ],
      },
      { kind: "p", text: "Someone who checks in 7 times a week earns **1.8×** what someone who checks in twice earns. Not 3.5×. The game pays for showing up, not for living in the gym." },
    ],
  },
  {
    id: "skills",
    label: "Skills",
    title: "Skills",
    lede: "You have nine skills. XP comes only from check-ins and from things check-ins trigger, and it is paid the way Old School RuneScape pays it.",
    blocks: [
      { kind: "p", text: "A check-in is one **training session**: half an hour of swings against your Slayer task, with the best scimitar your Attack level can wield, the best full armour set your Defence level can wear, and the strongest prayers your Prayer level allows. The game works out your max hit and your chance to hit with the wiki's formulas, adds up the damage, and pays XP on it. The monster's stats, the scimitar and armour bonuses and the Slayer tables are all pulled from the OSRS wiki; nothing is made up." },
      {
        kind: "table",
        columns: ["Skill", "How it grows"],
        rows: [
          ["Hitpoints", "4/3 XP per point of damage you deal. Everybody starts at Hitpoints 10."],
          [
            "Attack / Strength / Defence",
            "4 XP per point of damage to the skill your **combat style** trains: Accurate → Attack, Aggressive → Strength, Defensive → Defence. Controlled pays 4/3 to each of the three. `/style` sets it. Attack unlocks scimitars (rune at 40, dragon at 60), Strength raises your max hit, Defence unlocks armour and keeps you from eating through your food.",
          ],
          [
            "Slayer",
            "Every kill on your task pays the monster's Slayer XP (usually its Hitpoints). Verified check-ins: +500 × the weight for the author, +50 per extra verification. Verifying someone else: +100, paid on your own next check-in.",
          ],
          ["Prayer", "The bones your kills drop, buried: 4.5 for bones, 15 for big bones, 72 for dragon bones, up to 110 for infernal ashes. A Chapel is a gilded altar: 250%, then 300%, then 350%. Prayer unlocks the real prayers: Ultimate Strength at 31, Piety at 70."],
          ["Woodcutting", "The logs you carry to the town on each check-in, at the XP of the best tree your level can cut: 25 for logs, 67.5 for willows at 30, 175 for yews at 60."],
          ["Mining / Fishing", "Your workers' sacks, from week 13 onward, at the XP of the best ore or fish your level can take: coal at 30, lobsters at 40. A session handles up to 100 of each."],
        ],
      },
      { kind: "p", text: "Higher levels and better gear make every session pay more: a bigger max hit, more hits landing, tougher monsters from a higher Slayer master with bigger bones and more Slayer XP per kill. Two a week in week 40 earns several times what two a week earned in week 1." },
      { kind: "p", text: "The XP table is RuneScape's, exactly. Level 99 takes 13,034,431 XP." },
      {
        kind: "table",
        columns: ["Level", "XP"],
        rows: [
          ["2", "83"],
          ["10", "1,154"],
          ["20", "4,470"],
          ["30", "13,363"],
          ["40", "37,224"],
          ["50", "101,333"],
          ["60", "273,742"],
          ["70", "737,627"],
          ["92", "6,517,253"],
          ["99", "13,034,431"],
        ],
      },
      { kind: "note", text: "Two check-ins a week, every week, reaches Dragon (Defence 60) in week 52. Five a week gets there around week 33. Once a week ends the year in Adamant or Rune. The session length is the one number tuned to that; everything else is the game's own." },
    ],
  },
  {
    id: "tiers",
    label: "Tiers",
    title: "Tiers",
    lede: "Your tier is the armour set your Defence level can wear: the game's own requirements. Your Attack level picks your scimitar the same way. Both are used in every session.",
    blocks: [
      {
        kind: "table",
        columns: ["Tier", "Defence (armour) / Attack (scimitar)", "Title", "Scimitar bonus"],
        rows: [
          ["Bronze", "1", "", "+7 slash, +6 strength"],
          ["Iron", "1", "", "+10, +9"],
          ["Steel", "5", "", "+15, +14"],
          ["Black", "10", "", "+19, +14"],
          ["Mithril", "20", "Regular", "+21, +20"],
          ["Adamant", "30", "Veteran", "+29, +28"],
          ["Rune", "40", "Champion", "+45, +44"],
          ["Dragon", "60", "Dragon Slayer", "+67, +66"],
        ],
      },
      { kind: "p", text: "Rune (t), Rune (g) and the rest are clue rewards, not levels. They live in the collection log. The Slayer helmet (400 Slayer points) gives +16⅔% accuracy and damage on task, as in the game. The Amulet of glory (t) from a medium clue adds its +10 attack and +6 strength." },
    ],
  },
  {
    id: "events",
    label: "Random events",
    title: "Random events",
    lede: "Each check-in has a 1 in 6 chance of a random event. A Tavern in the town makes it 1 in 5, then 1 in 4. If you go 12 check-ins without one, the next is guaranteed. The weight column is how likely each event is compared to the others.",
    blocks: [
      {
        kind: "table",
        columns: ["Event", "Weight", "What happens"],
        rows: [
          ["Genie", "30", "A lamp worth 10 × the level of the skill you rub it into, as in the game. Leave it 14 days and it rubs itself into Hitpoints."],
          ["Mysterious Old Man", "15", "150 of one resource goes to the town."],
          ["Drunken Dwarf", "12", "A Ring of Life. If you already hold the maximum, 200 coins instead."],
          ["Evil Chicken", "10", "+500 Defence XP."],
          ["Sandwich Lady", "8", "+500 Hitpoints XP."],
          ["Beekeeper", "8", "Your workers gather 25% more for 24 hours."],
          ["Quiz Master", "7", "A three-button trivia question. Right: +500 combat XP. Wrong: 50 coins go to the town."],
          ["Freaky Forester", "5", "Repairs the town's most damaged building, or leaves logs if nothing needs repair."],
          ["Drill Demon", "3", "Sergeant Damien's exercises: 10 × the level in a random one of Attack, Strength or Defence."],
          ["Prison Pete", "2", "Two lamps."],
        ],
      },
      { kind: "note", text: "No event ever hurts you. Every one is a gift or nothing." },
    ],
  },
  {
    id: "form",
    label: "Form, streaks, Rings",
    title: "Form, streaks, Rings",
    blocks: [
      {
        kind: "ul",
        items: [
          "**Form** means 2 or more check-ins in the last 7 days. Your sheet shows it as dots.",
          "**Form weeks** are weeks in a row with 2 or more check-ins. That is your streak.",
          "A **Ring of Life** saves your streak once. You earn Rings; you cannot buy them. Weeks 1–8: one Ring per 3 Form weeks. From week 9: one per 2. You can hold 2, or 3 after Graduation. The Last Recall relic raises the cap by one and gives a Ring every Form week.",
          "If a week ends with exactly one check-in, a Ring is spent for you and your streak survives. A week with zero check-ins breaks the streak. No Ring saves a zero.",
          "**Graduation** is your 13th week as a player.",
        ],
      },
      { kind: "p", text: "**The Restless Lifter** is the comeback quest. If you check in after 14 or more days away, it starts. Check in 3 times in the next 14 days and you get a 7,500 XP antique lamp, a Ring, and a new streak starting at 1." },
      { kind: "p", text: "The big lamps the campaign hands out (quests, Foundings, raids, caskets) are the Achievement Diary's antique lamps: 2,500, 7,500, 15,000 or 50,000 XP into any skill." },
    ],
  },
  {
    id: "clues",
    label: "Clue scrolls",
    title: "Clue scrolls",
    lede: "Each check-in has a 1 in 12 chance of dropping a clue scroll. You can hold one at a time. Its tier depends on the monster you were fighting: chickens and hill giants drop easy clues, greater demons hard ones, black demons elite. `/clue` shows your steps.",
    blocks: [
      {
        kind: "table",
        columns: ["Tier", "Hitpoints", "Steps", "XP", "Coins", "Unique"],
        rows: [
          ["Easy", "1–19", "2", "1,500", "100", "1 in 3"],
          ["Medium", "20–39", "3", "3,000", "200", "1 in 4"],
          ["Hard", "40–54", "4", "4,500", "400", "1 in 5"],
          ["Elite", "55–59", "5", "6,000", "700", "1 in 6"],
          ["Master", "60+", "6", "8,000", "1,000", "1 in 8"],
        ],
      },
      { kind: "p", text: "A clue is a short list of steps. Do them in **any order**, one step per check-in. Steps are things any player can do:" },
      {
        kind: "ul",
        items: [
          "A check-in with a verified photo. A check-in with a verified video.",
          "A weekend check-in. A Monday check-in.",
          "A check-in before 8am. A check-in after 8pm.",
          "Two days in a row. The same day as two other players.",
          "Deliver 200 or more resources to the town. Write a note of 20 words or more.",
          "Verify someone. A check-in that completes a Slayer task. A check-in during a raid week. Bring in a full sack.",
        ],
      },
      { kind: "note", text: "Three steps need systems that arrive later: delivering 200+ needs the town, a raid-week check-in needs raids, and a full sack needs workers. You are never given a step you cannot do yet." },
      { kind: "p", text: "When the last step is done, the casket opens. You get the XP and coins from the table, and a chance at a unique. Unfinished clues are lost at each Founding. The 24 uniques only decorate your sheet: Ranger boots, Robin hood hat, 3rd age full helmet, a Bloodhound pet, and twenty more." },
    ],
  },
  {
    id: "verification",
    label: "Verification",
    title: "Verification",
    blocks: [
      {
        kind: "ul",
        items: [
          "Check in with a photo or video and your check-in gets a Verify button for 72 hours.",
          "Any fresh player except you can press it. One press is enough.",
          "**You get:** combat XP × 1.5 and +1,000 Slayer XP. Each extra verification adds +100, up to three.",
          "**The verifier gets:** +250 Slayer XP, paid on their own next check-in within 7 days. At most 3 verifications a day count.",
        ],
      },
    ],
  },
  {
    id: "slayer",
    label: "Slayer tasks",
    title: "Slayer tasks",
    lede: "You always have a Slayer task, and every check-in is a training session against it. `/task` shows it.",
    blocks: [
      { kind: "p", text: "A **Slayer master** gives you the task, drawn from that master's real assignment table on the OSRS wiki, with the real amounts and the real Slayer level requirements. Which master you have depends on your combat level, as in the game. A higher master's monsters have more Hitpoints (so more Slayer XP per kill), hit harder, and drop bigger bones." },
      {
        kind: "table",
        columns: ["Master", "Combat level", "Typical task", "Points per task"],
        rows: [
          ["Turael", "any", "15–30 birds, cows, goblins, rats, spiders, skeletons, zombies…", "0"],
          ["Mazchna", "20", "30–50 hill giants, hobgoblins, ghouls, cockatrice, pyrefiends, ice warriors…", "2"],
          ["Vannaka", "40", "40–90 moss giants, ogres, fire giants, lesser demons, bloodvelds, blue dragons…", "4"],
          ["Chaeldar", "70", "70–130 greater demons, hellhounds, gargoyles, nechryael, black demons…", "10"],
          ["Nieve", "85", "120–185 abyssal demons, dark beasts, smoke devils, black dragons…", "12"],
          ["Duradel", "100, and Slayer 50", "130–200 of the hardest things", "15"],
        ],
      },
      {
        kind: "ul",
        items: [
          "A session's kills come from its damage: max hit × hit chance × swings, divided by the monster's Hitpoints. A new player kills a dozen chickens; a Rune player kills twenty hill giants; a Dragon player kills a handful of abyssal demons.",
          "Every kill on task pays the monster's Slayer XP straight away: 35 for a hill giant, 150 for an abyssal demon.",
          "Finish the task and you get the master's Slayer points, and the next task on the spot. Your 10th task in a row pays 5× points. Your 50th pays 15×. Your 100th pays 25×.",
          "Tasks do not expire. Skipping one costs 30 points and resets nothing but the task.",
          "A master never assigns what your Slayer level cannot damage: no abyssal demons before Slayer 85.",
        ],
      },
      { kind: "p", text: "**Slayer points** buy the same three things as the Slayer Rewards shop:" },
      {
        kind: "table",
        columns: ["Reward", "Points"],
        rows: [
          ["Skip your current task (`/task skip`)", "30"],
          ["10,000 Slayer XP (`/task xp`)", "100"],
          ["The Slayer helmet: +16⅔% accuracy and damage on task, and the \"Slayer Master\" title (`/task helmet`)", "400"],
        ],
      },
    ],
  },
  {
    id: "log",
    label: "Collection log",
    title: "Collection log",
    lede: "The collection log is a checklist of 90 things you can earn, in eight groups. `/log` shows yours.",
    blocks: [
      {
        kind: "table",
        columns: ["Category", "Entries"],
        rows: [
          ["Random events", "12"],
          ["Clue uniques", "24"],
          ["Boss heads", "7"],
          ["Pets", "6"],
          ["Titles", "8"],
          ["Holiday", "7"],
          ["Milestones", "17"],
          ["Skills to 50", "9"],
        ],
      },
      {
        kind: "ul",
        items: ["30 entries: the Collector title.", "60 entries: a pet.", "90 entries: the Completionist cape."],
      },
    ],
  },
  {
    id: "camp",
    label: "The camp and the town",
    title: "The camp and the town",
    lede: "The camp exists from day one. In week 13 (Founding I) it becomes a town with workers and buildings. `/town` shows it.",
    blocks: [
      { kind: "p", text: "Every check-in carries 20 coins and 10 logs to the town. Both are multiplied by your check-in's weight and by your tier. Ore is smelted at the Furnace: 5 ore makes 1 bar." },
      { kind: "p", text: "**Quiet-day rule.** If fewer than a quarter of the roster checks in on a day, every store in the town loses 1%. Never more than 1%. Nobody is named." },
      { kind: "p", text: "**Workers** gather one resource each, once an hour, into a sack. A Miner gathers ore, a Woodcutter logs, a Fisher fish, a Merchant coins. The sack fills for 96 hours (plus 24 hours per Bank level), then stops. It empties into the town on your next check-in." },
      {
        kind: "ul",
        items: [
          "**Worker slots:** 1, plus 1 more for every 15 Hitpoints levels.",
          "**Recruiting** a worker costs 300 coins × the number of workers you already own. Your first is free at the Founding.",
          "Workers eat 6 fish a day. A hungry worker works at half speed.",
          "You must be fresh to use `/recruit kind`, `/upgrade`, `/build building` and `/repair building`.",
          "If you are silent for 21 days, your workers work for the town at half speed until you come back.",
        ],
      },
      {
        kind: "table",
        columns: ["Worker tier", "Per hour", "Upgrade cost", "Needs"],
        rows: [
          ["Bronze", "2", "Free at the Founding", ""],
          ["Iron", "3", "150 coins, 20 ore", ""],
          ["Steel", "4", "250 coins, 40 ore", ""],
          ["Black", "5", "400 coins, 60 ore, 20 logs", ""],
          ["Mithril", "7", "700 coins, 100 ore, 40 logs", ""],
          ["Adamant", "9", "1,200 coins, 160 ore, 80 logs", ""],
          ["Rune", "12", "2,000 coins, 250 ore, 120 logs, 20 bars", "Furnace L2"],
          ["Dragon", "16", "3,500 coins, 400 ore, 200 logs, 50 bars", "Furnace L3 and a Dragon-tier owner"],
        ],
      },
      { kind: "p", text: "**Buildings** are paid for from the town's stores. The table shows level 1 costs. Level 2 costs 2.5× and level 3 costs 6×. Buildings lose 3 condition a day. Repairs cost 2 logs per point. A building under 50% condition gives half its bonus." },
      {
        kind: "table",
        columns: ["Building", "Level 1", "From", "Effect"],
        rows: [
          ["Bank", "200 coins, 150 logs", "Act 2", "Sacks fill 24 hours longer per level"],
          ["Furnace", "300 coins, 200 logs", "Act 2", "Smelts ore into bars. L2 unlocks Rune workers, L3 Dragon"],
          ["Fishing Dock", "200 coins, 150 logs, 50 ore", "Act 2", "Fish +25% per level"],
          ["Lumber Mill", "200 coins, 150 logs, 50 ore", "Act 2", "Logs +25% per level"],
          ["Mine Cart", "200 coins, 150 logs, 50 ore", "Act 2", "Ore +25% per level"],
          ["Chapel", "300 coins, 200 logs", "Act 2", "A gilded altar: the bones from your kills pay 250%, then 300%, then 350%"],
          ["Tavern", "400 coins, 250 logs", "Act 2", "Random events 1 in 6 → 1 in 5 → 1 in 4 (two levels)"],
          ["Barracks", "600 coins, 300 logs, 100 ore", "Act 3", "Raid damage +10% per level"],
          ["Walls", "600 coins, 300 logs, 100 ore", "Act 3", "Raid heals −5 per miss per level"],
          ["Dragon Statue", "2,000 coins, 900 logs, 100 bars", "Act 4", "The finale. +10% to everything, forever"],
        ],
      },
    ],
  },
  {
    id: "votes",
    label: "Votes, relics, raids",
    title: "Votes, relics and raid weeks",
    lede: "Build votes start in Act 2. Relic picks happen at weeks 27 and 40. Raids can be proposed from Act 3. `/vote`, `/relics` and `/raid status` show where each stands.",
    blocks: [
      { kind: "p", text: "**Build votes.** Every Monday from Act 2, the bot lists up to four buildings the town can afford. Half the active roster must vote (rounded up, never fewer than 2). The vote closes after 48 hours. If too few voted, the same options come back next Monday." },
      { kind: "p", text: "**Relic picks.** At weeks 27 and 40 the roster is shown three relics and has 72 hours to pick one. If nobody votes, the first is picked. A relic lasts the rest of the year." },
      {
        kind: "table",
        columns: ["Relic", "Effect"],
        rows: [
          ["Xeric's Endurance", "Your 3rd and 4th check-ins weigh 0.75 instead of 0.5"],
          ["Trickster", "Random events give +4 bingo points"],
          ["Fire Sale", "Worker upgrades cost 25% less"],
          ["Production Master", "Worker output +20%"],
          ["Last Recall", "Ring cap +1 and a Ring every Form week"],
          ["Berserker", "Raid damage +25%"],
          ["Treasure Seeker", "Lamps are worth ×1.5"],
          ["Golden God", "+20 coins to the town per check-in"],
        ],
      },
      { kind: "p", text: "**Raid weeks** are optional hard mode. From Act 3, anyone can run `/raid propose`. The vote passes with 60% of the active roster and at least 3 yes votes. A Sit out button keeps you out with no penalty. The raid starts the next Monday, and the roster is frozen for the week." },
      {
        kind: "ul",
        items: [
          "**Boss HP** = roster size × 2.4 × (100 + 2 × the roster's average Hitpoints) × the boss multiplier.",
          "**Your damage** per check-in = (100 + 2 × your Hitpoints) × your check-in's weight × the Barracks bonus × Berserker.",
          "**The boss heals** 20 per roster member who is not in form, each day, up to 80. Each Walls level takes 5 off every heal.",
          "**Win:** everyone on the roster gets a lamp worth 100 × Hitpoints, at least 2,000 XP. Anyone with 3 or more check-ins that week gets a second. The town gets 1,000 coins and 200 bars.",
          "**Loss:** the town loses 15% of its stores, once, and every building loses 20 condition. Three losses lock raids for 4 weeks.",
        ],
      },
      {
        kind: "table",
        columns: ["Boss", "Order", "Multiplier"],
        rows: [
          ["Giant Mole", "1st", "×0.8 — proposed by the bot at week 27"],
          ["King Black Dragon", "2nd", "×1.0"],
          ["Kalphite Queen", "3rd", "×1.0"],
          ["Chaos Elemental", "4th", "×1.0"],
          ["Corporeal Beast", "5th", "×1.2"],
          ["Elvarg", "Act 4", "×2 HP over 14 days — proposed by the bot at week 50"],
        ],
      },
    ],
  },
  {
    id: "bingo",
    label: "Bingo and the shop",
    title: "Bingo and the shop",
    lede: "Each act has a 5×5 bingo card. Cells tick themselves when you do the thing. `/bingo` shows the card. `/shop` spends the points.",
    blocks: [
      {
        kind: "ul",
        items: [
          "Each cell pays its points once. A full line pays **+5**. A full card pays **+40**.",
          "When every active player has at least one line, the town gets a 500-coin crate.",
          "Acts 2–4 swap in worker, raid and Dragon cells for the ones you have outgrown.",
        ],
      },
      { kind: "p", text: "The Act 1 card, with points in brackets:" },
      {
        kind: "table",
        columns: ["B", "I", "N", "G", "O"],
        rows: [
          ["First check-in (1)", "Two check-ins in one week (2)", "A verified check-in (2)", "Check in before 8am (2)", "Reach Mithril (3)"],
          ["Check in with a note (1)", "A Saturday check-in (1)", "Verify three friends (2)", "Two days in a row (2)", "Three Form weeks in a row (3)"],
          ["Check in after 8pm (1)", "Rub a lamp (2)", "10 check-ins (3)", "A Sunday check-in (2)", "Same day as three others (2)"],
          ["A Monday check-in (1)", "Reach Adamant (3)", "A verified video (2)", "Two verified in one week (2)", "Four different weekdays in one week (2)"],
          ["A note that says PR (1)", "Beat the Quiz Master (2)", "Any skill to 30 (3)", "Six Form weeks in a row (3)", "Reach Rune (3)"],
        ],
      },
      { kind: "p", text: "**The shop** takes bingo points. It sells only cosmetics and small lamps. Rings of Life are never for sale." },
      {
        kind: "table",
        columns: ["Item", "Points", "Choices"],
        rows: [
          ["Small lamp", "15", "2,000 XP into a skill of your choice"],
          ["Sheet trim", "30", "Gold, silver, obsidian, third-age"],
          ["A title", "25", "of Lumbridge, the Relentless, Ironman, of the Wilderness, the Early Riser"],
          ["Name a worker", "10", ""],
          ["Town crate", "20", "A resource drop for the town"],
          ["Pet", "50", "Baby Mole, Chompy chick"],
          ["Act cape", "60", "The cape of the current act"],
        ],
      },
    ],
  },
  {
    id: "year",
    label: "The year",
    title: "The year",
    lede: "Launch is Monday 14 September 2026. The year is four acts of 13 weeks. Week 52 is 6–12 September 2027.",
    blocks: [
      {
        kind: "table",
        columns: ["Act", "Weeks", "Name", "What activates"],
        rows: [
          ["1", "1–13", "Lumbridge", "Skills, streaks, random events, clues, Slayer tasks, bingo, the camp"],
          ["2", "14–26", "Varrock", "Founding I: workers, sacks, buildings, build votes"],
          ["3", "27–39", "The Wilderness", "Relic picks, raid weeks, Barracks and Walls"],
          ["4", "40–52", "Dragon Slayer", "Dragon tier, the Dragon Statue, Elvarg, the finale"],
        ],
      },
      { kind: "p", text: "Each act ends in a **Founding**: the Town Hall gains a level, output rises 10%, the stores reset, and anyone in form for 6 or more of the act's 13 weeks gets a 15,000 XP Founding lamp." },
      { kind: "p", text: "Holidays: Halloween week 7, Thanksgiving week 11, Christmas weeks 15–16, Valentine's week 22, Easter week 28, Independence week 42." },
      { kind: "p", text: "On the 1st of every month the bot posts a campaign log: who was in form, what the town built, and what the month's lamps and clues added up to." },
    ],
  },
  {
    id: "commands",
    label: "Commands",
    title: "Commands",
    blocks: [
      {
        kind: "table",
        columns: ["Command", "What it does"],
        rows: [
          ["`/checkin [note] [photo]`", "Check in with a note or a photo. The morning post's Yes button does it without either; a photo sent after a Yes attaches to it."],
          ["`/play`", "Open your hub without checking in."],
          ["`/sheet [player] [public]`", "Your sheet, or someone else's. Public posts it to the channel."],
          ["`/join [ping]`", "Become a player. Pass ping to turn pings on at the same time."],
          ["`/leave`", "Retire. Sheet kept."],
          ["`/expedition weeks`", "Pause for 1–8 weeks."],
          ["`/pings on|off`", "Morning post and last call pings."],
          ["`/style`", "Accurate, Aggressive, Defensive, or Controlled."],
          ["`/lamp`", "Rub a held lamp into a skill."],
          ["`/clue`", "Your current clue trail."],
          ["`/task`", "Your current Slayer task: master, monster, kills so far, and your points."],
          ["`/task skip|xp|helmet`", "Spend Slayer points: skip the task (30), 10,000 Slayer XP (100), the Slayer helmet (400)."],
          ["`/log`", "Your collection log."],
          ["`/town`", "The town: stores, workers, buildings."],
          ["`/recruit kind`", "Hire a Miner, Woodcutter, Fisher, or Merchant."],
          ["`/upgrade`", "Take a worker up a tier."],
          ["`/build building`", "Put a building up, or take it up a level."],
          ["`/repair building`", "Spend logs on condition."],
          ["`/vote`", "This week's build vote."],
          ["`/relics`", "The relic pick, or the relics held."],
          ["`/raid status|propose`", "The current raid, or propose one from Act 3."],
          ["`/bingo`", "This act's card and your points."],
          ["`/shop`", "Spend bingo points. Slayer points are spent in `/task`."],
          ["`/freeze`", "Your Rings and streak state."],
          ["`/standings`", "This week's roster, weighted."],
          ["`/help`", "A short version of this page."],
          ["`/admin …`", "Admin only."],
        ],
      },
      { kind: "p", text: "Buttons: **Yes** and **No** on the morning post, **Join**, **Verify**, **Ping me**, **Sit out**, the hub buttons (**Lamp**, **Clue**, **Task**, **Sheet**, **Town**, **Log**, **Bingo**, **Shop**, **Votes**), the three quiz answers, the lamp skill picker, the vote options, and **Share to channel**." },
    ],
  },
  {
    id: "refuses",
    label: "What it refuses to do",
    title: "What this game refuses to do",
    blocks: [
      {
        kind: "ul",
        items: [
          "No buying your streak back. Rings are earned or they do not exist.",
          "Nothing rewards chat. Talk because you want to.",
          "No bad rolls. Every random event is a gift or nothing.",
          "Group harm is capped at 1% and nobody is named for it.",
          "No workout types to manage. You moved or you did not.",
          "People who have not joined are invisible. Nobody is guilted into a game they did not join.",
          "One morning post. One line and one loot card per check-in. That is the bot's whole footprint.",
        ],
      },
    ],
  },
];
